export const ECHR_ARTICLES: { number: string; title: string }[] = [
    { number: '1', title: 'Article 1 - Obligation to respect human rights' },
    { number: '2', title: 'Article 2 - Right to life' },
    { number: '2+1', title: 'Article 2 + Article 1' },
    { number: '2+3', title: 'Article 2 + Article 3' },
    { number: '2+6', title: 'Article 2 + Article 6' },
    { number: '2+13', title: 'Article 2 + Article 13' },
    { number: '2+17', title: 'Article 2 + Article 17' },
    { number: '2+P6-1', title: 'Article 2 + Protocol 6 Article 1' },
    { number: '2+P13-1', title: 'Article 2 + Protocol 13 Article 1' },
    { number: '2-1', title: 'Article 2-1 - Right to life (positive obligation)' },
    { number: '2-2', title: 'Article 2-2 - Exceptions to right to life (use of force)' },
    { number: '3', title: 'Article 3 - Prohibition of torture' },
    { number: '3+13', title: 'Article 3 + Article 13' },
    { number: '3+P6-1', title: 'Article 3 + Protocol 6 Article 1' },
    { number: '4', title: 'Article 4 - Prohibition of slavery and forced labour' },
    { number: '4+2', title: 'Article 4 + Article 2' },
    { number: '4-1', title: 'Article 4-1 - Prohibition of slavery' },
    { number: '4-2', title: 'Article 4-2 - Prohibition of servitude' },
    { number: '4-3', title: 'Article 4-3 - Prohibition of forced or compulsory labour' },
    { number: '4-3-a', title: 'Article 4-3-a - Work in ordinary course of detention' },
    { number: '5', title: 'Article 5 - Right to liberty and security' },
    { number: '5+13', title: 'Article 5 + Article 13' },
    { number: '5-1', title: 'Article 5-1 - Right to liberty and security (general)' },
    { number: '5-1-a', title: 'Article 5-1-a - Lawful detention after conviction' },
    {
        number: '5-1-b',
        title: 'Article 5-1-b - Lawful arrest or detention for non-compliance with court order'
    },
    {
        number: '5-1-c',
        title: 'Article 5-1-c - Lawful arrest or detention to bring before competent legal authority'
    },
    { number: '5-1-d', title: 'Article 5-1-d - Lawful detention of minors' },
    {
        number: '5-1-e',
        title: 'Article 5-1-e - Lawful detention to prevent spread of infectious diseases'
    },
    {
        number: '5-1-f',
        title: 'Article 5-1-f - Lawful arrest or detention to prevent unauthorised entry or deportation'
    },
    { number: '5-2', title: 'Article 5-2 - Right to be informed of reasons for arrest' },
    {
        number: '5-3',
        title: 'Article 5-3 - Right to be brought before a judge and trial within reasonable time'
    },
    { number: '5-3+5-1', title: 'Article 5-3 + Article 5-1' },
    { number: '5-4', title: 'Article 5-4 - Right to challenge lawfulness of detention' },
    { number: '5-4+5-1', title: 'Article 5-4 + Article 5-1' },
    { number: '5-5', title: 'Article 5-5 - Right to compensation for unlawful detention' },
    { number: '6', title: 'Article 6 - Right to a fair trial' },
    { number: '6+6-3', title: 'Article 6 + Article 6-3' },
    { number: '6+8', title: 'Article 6 + Article 8' },
    { number: '6+13', title: 'Article 6 + Article 13' },
    { number: '6+P1-1', title: 'Article 6 + Protocol 1 Article 1' },
    { number: '6-1', title: 'Article 6-1 - Right to a fair and public hearing' },
    { number: '6-2', title: 'Article 6-2 - Presumption of innocence' },
    { number: '6-3', title: 'Article 6-3 - Minimum rights in criminal proceedings' },
    { number: '6-3-a', title: 'Article 6-3-a - Right to be informed of accusation' },
    { number: '6-3-b', title: 'Article 6-3-b - Right to adequate time and facilities for defence' },
    {
        number: '6-3-c',
        title: 'Article 6-3-c - Right to defend oneself or through legal assistance'
    },
    { number: '6-3-d', title: 'Article 6-3-d - Right to examine witnesses' },
    { number: '6-3-e', title: 'Article 6-3-e - Right to free assistance of an interpreter' },
    { number: '7', title: 'Article 7 - No punishment without law' },
    { number: '7-1', title: 'Article 7-1 - No punishment without law' },
    { number: '7-2', title: 'Article 7-2 - Non-retroactivity exception' },
    { number: '8', title: 'Article 8 - Right to respect for private and family life' },
    { number: '8+2', title: 'Article 8 + Article 2' },
    { number: '8+9', title: 'Article 8 + Article 9' },
    { number: '8+11', title: 'Article 8 + Article 11' },
    { number: '8+13', title: 'Article 8 + Article 13' },
    { number: '8-1', title: 'Article 8-1 - Right to respect for private and family life' },
    {
        number: '8-2',
        title: 'Article 8-2 - Permissible interferences with private and family life'
    },
    { number: '9', title: 'Article 9 - Freedom of thought, conscience and religion' },
    { number: '9+13', title: 'Article 9 + Article 13' },
    { number: '9-1', title: 'Article 9-1 - Freedom of thought, conscience and religion' },
    {
        number: '9-2',
        title: 'Article 9-2 - Permissible limitations on freedom of thought, conscience and religion'
    },
    { number: '10', title: 'Article 10 - Freedom of expression' },
    { number: '10+8', title: 'Article 10 + Article 8' },
    { number: '10-1', title: 'Article 10-1 - Freedom of expression' },
    { number: '10-2', title: 'Article 10-2 - Permissible restrictions on freedom of expression' },
    { number: '11', title: 'Article 11 - Freedom of assembly and association' },
    { number: '11-1', title: 'Article 11-1 - Freedom of assembly and association' },
    {
        number: '11-2',
        title: 'Article 11-2 - Permissible restrictions on freedom of assembly and association'
    },
    { number: '12', title: 'Article 12 - Right to marry' },
    { number: '12-1', title: 'Article 12-1 - Right to marry' },
    { number: '13', title: 'Article 13 - Right to an effective remedy' },
    { number: '13+1', title: 'Article 13 + Article 1' },
    { number: '13+2', title: 'Article 13 + Article 2' },
    { number: '13+2-1', title: 'Article 13 + Article 2-1' },
    { number: '13+3', title: 'Article 13 + Article 3' },
    { number: '13+4', title: 'Article 13 + Article 4' },
    { number: '13+5', title: 'Article 13 + Article 5' },
    { number: '13+5-1', title: 'Article 13 + Article 5-1' },
    { number: '13+5-1-f', title: 'Article 13 + Article 5-1-f' },
    { number: '13+6', title: 'Article 13 + Article 6' },
    { number: '13+6-1', title: 'Article 13 + Article 6-1' },
    { number: '13+8', title: 'Article 13 + Article 8' },
    { number: '13+9', title: 'Article 13 + Article 9' },
    { number: '13+10', title: 'Article 13 + Article 10' },
    { number: '13+11', title: 'Article 13 + Article 11' },
    { number: '13+14', title: 'Article 13 + Article 14' },
    { number: '13+P1-1', title: 'Article 13 + Protocol 1 Article 1' },
    { number: '13+P1-2', title: 'Article 13 + Protocol 1 Article 2' },
    { number: '13+P4-3', title: 'Article 13 + Protocol 4 Article 3' },
    { number: '14', title: 'Article 14 - Prohibition of discrimination' },
    { number: '14+1', title: 'Article 14 + Article 1' },
    { number: '14+2', title: 'Article 14 + Article 2' },
    { number: '14+2-1', title: 'Article 14 + Article 2-1' },
    { number: '14+3', title: 'Article 14 + Article 3' },
    { number: '14+4', title: 'Article 14 + Article 4' },
    { number: '14+5', title: 'Article 14 + Article 5' },
    { number: '14+5-1', title: 'Article 14 + Article 5-1' },
    { number: '14+6', title: 'Article 14 + Article 6' },
    { number: '14+6-1', title: 'Article 14 + Article 6-1' },
    { number: '14+6-3-c', title: 'Article 14 + Article 6-3-c' },
    { number: '14+8', title: 'Article 14 + Article 8' },
    { number: '14+8-1', title: 'Article 14 + Article 8-1' },
    { number: '14+9', title: 'Article 14 + Article 9' },
    { number: '14+10', title: 'Article 14 + Article 10' },
    { number: '14+11', title: 'Article 14 + Article 11' },
    { number: '14+13', title: 'Article 14 + Article 13' },
    { number: '14+17', title: 'Article 14 + Article 17' },
    { number: '14+P1-1', title: 'Article 14 + Protocol 1 Article 1' },
    { number: '14+P1-1-1', title: 'Article 14 + Protocol 1 Article 1-1' },
    { number: '14+P1-2', title: 'Article 14 + Protocol 1 Article 2' },
    { number: '14+P4-2', title: 'Article 14 + Protocol 4 Article 2' },
    { number: '14+P12-1', title: 'Article 14 + Protocol 12 Article 1' },
    { number: '15', title: 'Article 15 - Derogation in time of emergency' },
    { number: '15+5', title: 'Article 15 + Article 5' },
    { number: '15+6', title: 'Article 15 + Article 6' },
    { number: '15-1', title: 'Article 15-1 - Derogation in time of emergency' },
    { number: '16', title: 'Article 16 - Restrictions on political activity of aliens' },
    { number: '17', title: 'Article 17 - Prohibition of abuse of rights' },
    { number: '18', title: 'Article 18 - Limitation on use of restrictions on rights' },
    { number: '18+5', title: 'Article 18 + Article 5' },
    { number: '18+5-1', title: 'Article 18 + Article 5-1' },
    { number: '18+5-1-f', title: 'Article 18 + Article 5-1-f' },
    { number: '19', title: 'Article 19 - Establishment of the Court' },
    { number: '20', title: 'Article 20 - Number of Judges' },
    { number: '25', title: 'Article 25 - Registry' },
    { number: '25+26', title: 'Article 25 + Article 26' },
    { number: '25-1', title: 'Article 25-1 - Registry (function)' },
    { number: '26', title: 'Article 26 - Plenary Court' },
    { number: '27', title: 'Article 27 - Committees, Chambers and Grand Chamber' },
    { number: '27-1-b', title: 'Article 27-1-b - Committees' },
    { number: '27-2', title: 'Article 27-2 - Chambers' },
    { number: '28', title: 'Article 28 - Declarations of inadmissibility by committees' },
    { number: '28-1-a', title: 'Article 28-1-a - Declarations of inadmissibility (unanimous)' },
    { number: '28-b', title: 'Article 28-b - Declarations of inadmissibility (merits)' },
    { number: '29', title: 'Article 29 - Decisions by Chambers on admissibility and merits' },
    { number: '29-3', title: 'Article 29-3 - Decisions by Chambers (relinquishment)' },
    { number: '30', title: 'Article 30 - Relinquishment of jurisdiction to the Grand Chamber' },
    { number: '30-1-a', title: 'Article 30-1-a - Relinquishment (serious question)' },
    { number: '30-1-b', title: 'Article 30-1-b - Relinquishment (inconsistency)' },
    { number: '30-1-c', title: 'Article 30-1-c - Relinquishment (objection)' },
    { number: '32', title: 'Article 32 - Jurisdiction of the Court' },
    { number: '33', title: 'Article 33 - Inter-State cases' },
    { number: '34', title: 'Article 34 - Individual applications' },
    { number: '35', title: 'Article 35 - Admissibility criteria' },
    { number: '35-1', title: 'Article 35-1 - Admissibility criteria (general)' },
    {
        number: '35-2',
        title: 'Article 35-2 - Admissibility criteria (anonymous/substantially the same)'
    },
    { number: '35-2-b', title: 'Article 35-2-b - Admissibility criteria (substantially the same)' },
    { number: '35-3', title: 'Article 35-3 - Admissibility criteria (competence)' },
    { number: '35-3-a', title: 'Article 35-3-a - Admissibility criteria (manifestly ill-founded)' },
    { number: '35-4', title: 'Article 35-4 - Admissibility criteria (rejection)' },
    { number: '36', title: 'Article 36 - Third party intervention' },
    { number: '36-2', title: 'Article 36-2 - Third party intervention (interest of justice)' },
    { number: '37', title: 'Article 37 - Striking out applications' },
    { number: '37-1', title: 'Article 37-1 - Striking out applications (general)' },
    { number: '37-1-a', title: 'Article 37-1-a - Striking out applications (no justification)' },
    { number: '37-1-b', title: 'Article 37-1-b - Striking out applications (resolved)' },
    { number: '37-1-c', title: 'Article 37-1-c - Striking out applications (other grounds)' },
    { number: '37-2', title: 'Article 37-2 - Striking out applications (restoration)' },
    { number: '38', title: 'Article 38 - Examination of the case' },
    { number: '38-1', title: 'Article 38-1 - Examination of the case (general)' },
    { number: '38-1-a', title: 'Article 38-1-a - Examination (adversarial)' },
    { number: '38-1-b', title: 'Article 38-1-b - Friendly settlement' },
    { number: '39', title: 'Article 39 - Finding of a friendly settlement' },
    { number: '41', title: 'Article 41 - Just satisfaction' },
    { number: '43', title: 'Article 43 - Referral to the Grand Chamber' },
    { number: '46', title: 'Article 46 - Binding force and execution of judgments' },
    { number: '46-1', title: 'Article 46-1 - Binding force' },
    { number: '46-2', title: 'Article 46-2 - Execution of judgments' },
    { number: '47', title: 'Article 47 - Advisory opinions' },
    { number: '52', title: 'Article 52 - Finality of judgments' },
    { number: '53', title: 'Article 53 - Safeguard for existing human rights' },
    { number: '55', title: 'Article 55 - Exclusion of other means of dispute settlement' },
    { number: '57', title: 'Article 57 - Reservations' },
    { number: '58', title: 'Article 58 - Denunciation' },
    { number: '64', title: 'Article 64 - Reservations (former numbering)' },
    { number: 'P1-1', title: 'Protocol 1 Article 1 - Protection of property' },
    { number: 'P1-1-1', title: 'Protocol 1 Article 1-1 - Peaceful enjoyment of property' },
    { number: 'P1-1-2', title: 'Protocol 1 Article 1-2 - Control of use of property' },
    { number: 'P1-2', title: 'Protocol 1 Article 2 - Right to education' },
    { number: 'P1-3', title: 'Protocol 1 Article 3 - Right to free elections' },
    { number: 'P1-4', title: 'Protocol 1 Article 4 - Application' },
    { number: 'P4-1', title: 'Protocol 4 Article 1 - Prohibition of imprisonment for debt' },
    { number: 'P4-2', title: 'Protocol 4 Article 2 - Freedom of movement' },
    { number: 'P4-2-1', title: 'Protocol 4 Article 2-1 - Freedom of movement (general)' },
    {
        number: 'P4-2-2',
        title: 'Protocol 4 Article 2-2 - Freedom of movement (restrictions choice)'
    },
    { number: 'P4-2-3', title: 'Protocol 4 Article 2-3 - Freedom of movement (restrictions)' },
    { number: 'P4-3', title: 'Protocol 4 Article 3 - Prohibition of expulsion of nationals' },
    { number: 'P4-3+13', title: 'Protocol 4 Article 3 + Article 13' },
    { number: 'P4-3-1', title: 'Protocol 4 Article 3-1 - Expulsion of nationals' },
    {
        number: 'P4-4',
        title: 'Protocol 4 Article 4 - Prohibition of collective expulsion of aliens'
    },
    { number: 'P4-5', title: 'Protocol 4 Article 5 - Territorial application' },
    { number: 'P5-7', title: 'Protocol 5 Article 7 - Territorial application' },
    { number: 'P6-1', title: 'Protocol 6 Article 1 - Abolition of the death penalty' },
    { number: 'P6-2', title: 'Protocol 6 Article 2 - Death penalty in time of war' },
    {
        number: 'P7-1',
        title: 'Protocol 7 Article 1 - Procedural safeguards relating to expulsion of aliens'
    },
    {
        number: 'P7-1-1',
        title: 'Protocol 7 Article 1-1 - Procedural safeguards (expulsion of aliens)'
    },
    { number: 'P7-2', title: 'Protocol 7 Article 2 - Right of appeal in criminal matters' },
    { number: 'P7-3', title: 'Protocol 7 Article 3 - Compensation for wrongful conviction' },
    { number: 'P7-4', title: 'Protocol 7 Article 4 - Right not to be tried or punished twice' },
    { number: 'P7-5', title: 'Protocol 7 Article 5 - Equality between spouses' },
    { number: 'P12-1', title: 'Protocol 12 Article 1 - General prohibition of discrimination' },
    { number: 'P13-1', title: 'Protocol 13 Article 1 - Abolition of the death penalty' }
];

export const RESPONDENT_STATE_CODES: Record<string, string> = {
    'Albania': 'ALB',
    'Andorra': 'AND',
    'Armenia': 'ARM',
    'Austria': 'AUT',
    'Azerbaijan': 'AZE',
    'Belgium': 'BEL',
    'Bosnia and Herzegovina': 'BIH',
    'Bulgaria': 'BGR',
    'Croatia': 'HRV',
    'Cyprus': 'CYP',
    'Czech Republic': 'CZE',
    'Denmark': 'DNK',
    'Estonia': 'EST',
    'Finland': 'FIN',
    'France': 'FRA',
    'Georgia': 'GEO',
    'Germany': 'DEU',
    'Greece': 'GRC',
    'Hungary': 'HUN',
    'Iceland': 'ISL',
    'Ireland': 'IRL',
    'Italy': 'ITA',
    'Latvia': 'LVA',
    'Liechtenstein': 'LIE',
    'Lithuania': 'LTU',
    'Luxembourg': 'LUX',
    'Malta': 'MLT',
    'Moldova': 'MDA',
    'Monaco': 'MCO',
    'Montenegro': 'MNE',
    'Netherlands': 'NLD',
    'North Macedonia': 'MKD',
    'Norway': 'NOR',
    'Poland': 'POL',
    'Portugal': 'PRT',
    'Romania': 'ROU',
    'San Marino': 'SMR',
    'Serbia': 'SRB',
    'Slovakia': 'SVK',
    'Slovenia': 'SVN',
    'Spain': 'ESP',
    'Sweden': 'SWE',
    'Switzerland': 'CHE',
    'Turkey': 'TUR',
    'Ukraine': 'UKR',
    'United Kingdom': 'GBR'
};

export const RESPONDENT_STATE_LABELS: Record<string, string> = Object.fromEntries(
    Object.entries(RESPONDENT_STATE_CODES).map(([label, code]) => [code, label])
);

export const RESPONDENT_STATES: string[] = Object.keys(RESPONDENT_STATE_CODES);

export const RESPONDENT_STATE_ALIASES: Record<string, string> = {
    'uk': 'United Kingdom',
    'the uk': 'United Kingdom',
    'britain': 'United Kingdom',
    'great britain': 'United Kingdom',
    'england': 'United Kingdom',
    'verenigd koninkrijk': 'United Kingdom',
    'vk': 'United Kingdom',
    'the netherlands': 'Netherlands',
    'holland': 'Netherlands',
    'nederland': 'Netherlands',
    'bosnia': 'Bosnia and Herzegovina',
    'bosnie en herzegovina': 'Bosnia and Herzegovina',
    'czech': 'Czech Republic',
    'czechia': 'Czech Republic',
    'tsjechie': 'Czech Republic',
    'macedonia': 'North Macedonia',
    'noord macedonie': 'North Macedonia',
    'noord-macedonie': 'North Macedonia',
    'republic of moldova': 'Moldova',
    'moldavie': 'Moldova',
    'albanie': 'Albania',
    'andorra': 'Andorra',
    'armenie': 'Armenia',
    'oostenrijk': 'Austria',
    'azerbeidzjan': 'Azerbaijan',
    'belgie': 'Belgium',
    'bulgarije': 'Bulgaria',
    'kroatie': 'Croatia',
    'cyprus': 'Cyprus',
    'denemarken': 'Denmark',
    'estland': 'Estonia',
    'finland': 'Finland',
    'frankrijk': 'France',
    'georgie': 'Georgia',
    'duitsland': 'Germany',
    'griekenland': 'Greece',
    'hongarije': 'Hungary',
    'ijsland': 'Iceland',
    'ierland': 'Ireland',
    'italie': 'Italy',
    'letland': 'Latvia',
    'liechtenstein': 'Liechtenstein',
    'litouwen': 'Lithuania',
    'luxemburg': 'Luxembourg',
    'malta': 'Malta',
    'monaco': 'Monaco',
    'montenegro': 'Montenegro',
    'noorwegen': 'Norway',
    'polen': 'Poland',
    'portugal': 'Portugal',
    'roemenie': 'Romania',
    'san marino': 'San Marino',
    'servie': 'Serbia',
    'slowakije': 'Slovakia',
    'slovenie': 'Slovenia',
    'spanje': 'Spain',
    'zweden': 'Sweden',
    'zwitserland': 'Switzerland',
    'turkije': 'Turkey',
    'oekraine': 'Ukraine'
};

export const RECHTSPRAAK_INSTANCES: string[] = [
    'Hoge Raad',
    'Raad van State',
    'Centrale Raad van Beroep',
    'College van Beroep voor het bedrijfsleven',
    'Gerechtshof Amsterdam',
    'Gerechtshof Arnhem-Leeuwarden',
    'Gerechtshof Den Haag',
    "Gerechtshof 's-Hertogenbosch",
    'Rechtbank Amsterdam',
    'Rechtbank Den Haag',
    'Rechtbank Gelderland',
    'Rechtbank Limburg',
    'Rechtbank Midden-Nederland',
    'Rechtbank Noord-Holland',
    'Rechtbank Noord-Nederland',
    'Rechtbank Oost-Brabant',
    'Rechtbank Overijssel',
    'Rechtbank Rotterdam',
    'Rechtbank Zeeland-West-Brabant'
];

export const RECHTSPRAAK_DOMAINS: string[] = [
    'Bestuursrecht',
    'Civiel recht',
    'Strafrecht',
    'Belastingrecht',
    'Socialezekerheidsrecht',
    'Vreemdelingenrecht',
    'Ambtenarenrecht',
    'Europees recht',
    'Internationaal publiekrecht',
    'Insolventierecht',
    'Personen- en familierecht',
    'Arbeidsrecht',
    'Verbintenissenrecht',
    'Goederenrecht',
    'Ondernemingsrecht',
    'Intellectueel-eigendomsrecht',
    'Mededingingsrecht'
];

export const RECHTSPRAAK_DOMAIN_ALIASES: { pattern: string; value: string }[] = [
    { pattern: 'administrative law', value: 'Bestuursrecht' },
    { pattern: 'public law', value: 'Bestuursrecht' },
    { pattern: 'civil law', value: 'Civiel recht' },
    { pattern: 'criminal law', value: 'Strafrecht' },
    { pattern: 'tax law', value: 'Belastingrecht' },
    { pattern: 'social security law', value: 'Socialezekerheidsrecht' },
    { pattern: 'immigration law', value: 'Vreemdelingenrecht' },
    { pattern: 'aliens law', value: 'Vreemdelingenrecht' },
    { pattern: 'civil service law', value: 'Ambtenarenrecht' },
    { pattern: 'european law', value: 'Europees recht' },
    { pattern: 'public international law', value: 'Internationaal publiekrecht' },
    { pattern: 'international public law', value: 'Internationaal publiekrecht' },
    { pattern: 'insolvency law', value: 'Insolventierecht' },
    { pattern: 'family law', value: 'Personen- en familierecht' },
    { pattern: 'persons and family law', value: 'Personen- en familierecht' },
    { pattern: 'labour law', value: 'Arbeidsrecht' },
    { pattern: 'employment law', value: 'Arbeidsrecht' },
    { pattern: 'contract law', value: 'Verbintenissenrecht' },
    { pattern: 'law of obligations', value: 'Verbintenissenrecht' },
    { pattern: 'obligations law', value: 'Verbintenissenrecht' },
    { pattern: 'property law', value: 'Goederenrecht' },
    { pattern: 'company law', value: 'Ondernemingsrecht' },
    { pattern: 'corporate law', value: 'Ondernemingsrecht' },
    { pattern: 'intellectual property', value: 'Intellectueel-eigendomsrecht' },
    { pattern: 'intellectual property law', value: 'Intellectueel-eigendomsrecht' },
    { pattern: 'competition law', value: 'Mededingingsrecht' },
    { pattern: 'antitrust law', value: 'Mededingingsrecht' }
];

export const IMPORTANCE_LEVELS: { value: number; label: string }[] = [
    { value: 1, label: 'Key case' },
    { value: 2, label: 'Important' },
    { value: 3, label: 'Moderate' },
    { value: 4, label: 'Low importance' }
];

export const DOCUMENT_TYPES: string[] = [
    'Judgment',
    'Decision',
    'Advisory opinion',
    'Communicated case'
];

export const DOCUMENT_TYPE_LABELS_ECHR: Record<string, string> = {
    'JUD': 'Judgment',
    'DEC': 'Decision',
    'COM': 'Communicated Case',
    'CLIN': 'Clinical Note',
    'PR': 'Press Release',
    'OTHER': 'Other',
    'CC': 'Communicated Case'
};

export const DOCUMENT_TYPE_LABELS_RS: Record<string, string> = {
    'DEC': 'Uitspraak',
    'OPI': 'Conclusie'
};

export const DOCUMENT_TYPE_LABELS: Record<string, string> = {
    ...DOCUMENT_TYPE_LABELS_ECHR,
    ...DOCUMENT_TYPE_LABELS_RS,
    'DEC': 'Decision / Uitspraak' // Fallback for mixed contexts
};

export const LANGUAGE_LABELS: Record<string, string> = {
    'ENG': 'English',
    'FRA': 'French',
    'FRE': 'French',
    'NLD': 'Dutch',
    'DEU': 'German',
    'GER': 'German',
    'ITA': 'Italian',
    'ESP': 'Spanish',
    'UNK': 'Unknown',
    'RUS': 'Russian',
    'TUR': 'Turkish',
    'UKR': 'Ukrainian',
    'RON': 'Romanian',
    'POL': 'Polish',
    'SQI': 'Albanian',
    'ALB': 'Albanian',
    'HYE': 'Armenian',
    'ARM': 'Armenian',
    'AZE': 'Azerbaijani',
    'BOS': 'Bosnian',
    'BIH': 'Bosnian',
    'BUL': 'Bulgarian',
    'BGR': 'Bulgarian',
    'HRV': 'Croatian',
    'CES': 'Czech',
    'CZE': 'Czech',
    'DAN': 'Danish',
    'DNK': 'Danish',
    'EST': 'Estonian',
    'FIN': 'Finnish',
    'KAT': 'Georgian',
    'GEO': 'Georgian',
    'ELL': 'Greek',
    'GRC': 'Greek',
    'GRE': 'Greek',
    'HUN': 'Hungarian',
    'ISL': 'Icelandic',
    'GLE': 'Irish',
    'LAV': 'Latvian',
    'LAT': 'Latvian',
    'LIT': 'Lithuanian',
    'LTU': 'Lithuanian',
    'MKD': 'Macedonian',
    'MLT': 'Maltese',
    'CNR': 'Montenegrin',
    'NOR': 'Norwegian',
    'POR': 'Portuguese',
    'PRT': 'Portuguese',
    'SRP': 'Serbian',
    'SRB': 'Serbian',
    'SLK': 'Slovak',
    'SVK': 'Slovak',
    'SLV': 'Slovenian',
    'SVN': 'Slovenian',
    'SWE': 'Swedish',

};

export const ORIGINATING_BODY_LABELS: Record<string, string> = {
    'COURT': 'Court (Plenary)',
    'CHAMBER': 'Chamber',
    'GRANDCHAMBER': 'Grand Chamber',
    'COMMITTEE': 'Committee',
    'COMMISSION': 'Commission',
    'MINISTRY': 'Ministry'
};
